### ISSUE TITLE
Only apply font if it's already in localStorage

### ISSUE THREAD

**Issue by justmarkup** [bdadam/OptimizedWebfontLoading#2]
First of all, thanks for your research and the script - using it on some sites and it works great so far.

On a recent project I did a lot of testing and especially on low bandwdith FOUT is quite annoying (at least for me). That's why I only apply the font if the user already has been on the page and the font is stored in localStorage. 

I basically changed

```
loSto[localStorageCssKey] = styleElement.textContent = request.responseText;
```
to
```
loSto[localStorageCssKey] = request.responseText;
```

So maybe it's a good idea to add an option to apply the fonts only on second page load?

What do you think?

**Comment by bdadam** [comment]
Thanks for your idea. I added an optional parameter to the function which does what you need. I added a [new demo file](https://github.com/bdadam/OptimizedWebfontLoading/blob/master/build/demo-second-load.html) which illustrates the usage (just true as the 4th parameter).

To be honest, I'm not quite sure which case is the best, so I left the old behavior the default one.

**Comment by justmarkup** [comment]
Thanks!
